language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

# Run some basic sanity/end to end checks to make sure nothing got totally
# broken.
script:
    - "/usr/bin/env python3 --version"
    - "./taskutil --list"
    - "./taskutil --visualize > out.dot"
    - "./taskutil --run install-user-config --print_summary"
    - "./taskutil --clean"

