#!/usr/bin/env python3

import argparse
import sys
import os
import pathlib
import json
import subprocess
import pprint
import re
import traceback

class TaskError(Exception):
    pass

class Task:

    def __init__(this, provides, manifest):

        this.provides = provides
        this.manifest = manifest

        this.status = "not started"
        this.result = {}
        this.require_task = []
        this.run_script = []
        this.require_uname = []

    def do_run_script(this):
        results = {}
        for cmd in this.run_script:
            result = subprocess.check_output(cmd)
            result = result.decode("utf-8")
            result = result.strip()
            results[str(cmd)] = result
        if 'run-script' not in this.result:
            this.result["run-script"] = {}
        this.result["run-script"][cmd] = results

    def do_require_uname(this):
        uname_regex = re.compile(this.require_uname)
        uname = subprocess.check_output(["uname"]).decode("utf-8").strip()
        if not uname_regex.match(uname):
            this.result["require-uname"] = \
                    "Uname '{}' did not match regext {}'".format(
                        uname, this.require_uname)
        else:
            this.result["require-uname"] = \
                    "Uname '{}' matched regex '{}'".format(
                        uname, this.require_uname)

    def generate_graphviz(this):
        s = '\t"{}";\n'.format(this.provides)
        for t in this.require_task:
            s += t.generate_graphviz()
        for t in this.require_task:
            s += '\t"{}" -> "{}";\n'.format(this.provides, t.provides)
        return s

    def hydrate(this, tasks):
        for i in range(len(this.require_task)):
            if type(this.require_task[i]) is str:
                this.require_task[i] = tasks[this.require_task[i]]
            this.require_task[i].hydrate(tasks)


    def __str__(this):
        return "{}: {}".format(this.provides, this.status)


def print_warning(msg):
    sys.stderr.write("WARNING: {}\n".format(msg))
    sys.stderr.flush()

def index_tasks(taskstore):
    pathlist = pathlib.Path(taskstore).glob("*/task.json")
    tasks = {}
    for p in pathlist:
        with open(str(p), 'r') as f:
            j = json.load(f)
            name = j["provides"]
            if 'provides' not in j:
                print_warning("taskfile is missing 'provides' field: {}"
                              .format(p))
                continue
            if 'manifest' not in j:
                print_warning("taskfile is missing 'manifest' field: {}"
                              .format(p))
                continue
            if name in tasks:
                print_warning("duplicate provider for '{}' in: {}"
                              .format(name, p))
                continue

            task = Task(name, j["manifest"])

            if 'require-task' in j:
                task.require_task = j["require-task"]

            if 'run-script' in j:
                task.run_script = j["run-script"]

            if 'require-uname' in j:
                task.require_uname = j["require-uname"]

            tasks[name] = task

    return tasks



def main():
    parser = argparse.ArgumentParser()

    action_group = parser.add_mutually_exclusive_group()

    action_group.add_argument("--run", "-r", nargs="+", default=None,
            help="List one or more tasks to execute")

    action_group.add_argument("--list", "-l",
            default=False, action="store_true")

    action_group.add_argument("--visualize", "-s",
            default=False, action="store_true")

    args = parser.parse_args()

    base_dir = os.path.dirname(os.path.realpath(__file__))
    tasks_dir = os.path.join(base_dir, "tasks")

    tasks = index_tasks(tasks_dir)

    if args.list:
        sys.stdout.write("\n".join(tasks.keys()))
        sys.stdout.write("\n")
        sys.stdout.flush()
        exit(0)

    if args.visualize:
        master = Task("__master__", [])
        master.require_task = list(tasks.keys())

        master.hydrate(tasks)

        sys.stdout.write("digraph G {\n")
        sys.stdout.write(master.generate_graphviz())
        sys.stdout.write("}\n")

    if args.run is not None:
        master = Task("__master__", [])
        master.require_task = args.run

        master.hydrate(tasks)

        master.execute()


if __name__ == "__main__":
    main()
