run: build
	@echo "BUILD: executing java program"
	@java $(MAIN_FILE)

build: 
	@echo "BUILD: compiling project with javac..."
	javac $(MAIN_FILE).java
	@echo "BUILD: compilation complete"

clean:
	-rm *.class
